name: daim
description: "Kafe ve restoranlar için özel tasarlanmış modern sadakat yönetim sistemi!"
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.0+3
  cloud_firestore: ^5.6.2
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.1
  google_maps_flutter: ^2.10.0
  permission_handler: ^12.0.1
  geolocator: ^14.0.2
  provider: ^6.1.4
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  shared_preferences: ^2.4.0
  flutter_native_splash: ^2.4.4
  intl: ^0.20.2
  collection: ^1.19.0
  firebase_app_check: ^0.3.2+9
  mobile_scanner: ^7.0.1
  app_links: ^6.4.0
  http: ^1.4.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo.png
  branding: assets/logo.png
  branding_mode: bottom
  android: true
  ios: true
  fullscreen: true
  android_12:
    image: assets/logo.png
    icon_background_color: "#FFFFFF"
    branding: assets/logo.png
    branding_mode: bottom

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/star.png
    - assets/membership.png
    - assets/silver.png
    - assets/gold.png
    - assets/diamond.png
    - assets/premium.png
    - assets/languages/en.json
    - assets/languages/tr.json
    - assets/logo.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Bold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf