name: daim
description: "Kafe ve restoranlar için özel tasarlanmış modern sadakat yönetim sistemi!"
publish_to: 'none'
version: 1.2.0+19

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.0+3

  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_app_check: ^0.4.0
  firebase_crashlytics: ^5.0.1

  # Utils
  shared_preferences: ^2.3.3
  provider: ^6.1.5
  http: ^1.2.2
  collection: ^1.19.0
  intl: ^0.20.2
  vector_math: ^2.2.0

  # Maps & Location
  google_maps_flutter: ^2.10.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1

  # QR & Scanner
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.0.1

  # Deep links
  app_links: ^6.3.2

  # Launcher & Splash
  url_launcher: ^6.3.2
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

dependency_overrides:
  characters: ^1.4.1
  material_color_utilities: ^0.13.0
  meta: ^1.17.0
  package_info_plus: ^9.0.0
  test_api: ^0.7.7

flutter:
  uses-material-design: true
  assets:
    - assets/badges.json
    - assets/star.png
    - assets/membership.png
    - assets/silver.png
    - assets/gold.png
    - assets/diamond.png
    - assets/premium.png
    - assets/languages/en.json
    - assets/languages/tr.json
    - assets/logo.png

  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-Bold.otf